apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tk51srg7a-go 
  janus-idp.io/tekton: tk51srg7a-go
  backstage.io/kubernetes-id: tk51srg7a-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tk51srg7a-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  